### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by boyarskiy** [boyarskiy/react-simple-datepicker#1]
- [x] Ship gh-pages demo
- [x] Add examples of usage
- [x] Write more informing documentation
- [ ] More tests
- [ ] Setup test coverage
